In [ ]:
import tensorflow as tf
#Define a constant
a=tf.constant('hello world')
print(a)
print(a.numpy())

tf.Tensor(b'hello world', shape=(), dtype=string)
b'hello world'


In [ ]:
#Scalar constants
a=tf.constant(42)
b=tf.constant(3.14)
c=tf.constant("Hello,Tensorflow!")
print(a)
print(a.numpy())


tf.Tensor(42, shape=(), dtype=int32)
42


In [ ]:
#Vector constant
a=tf.constant([1,2,3])
b=tf.constant([1.0,2.0,3.0])
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
[1. 2. 3.]


In [ ]:
#Matrix constant
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[1.0,2.0],[3.0,4.0]])
print(a)
print(a.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]


In [ ]:
#Higher Dimensional Tensor constant
a=tf.constant([[[1,2,0],[3,4,0]],[[5,6,0],[7,8,0]]])
print(a)
print(a.numpy())

tf.Tensor(
[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]], shape=(2, 2, 3), dtype=int32)
[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]]


In [ ]:
#Boolean constant
a=tf.constant('true')
print(a)
print(a.numpy())

tf.Tensor(b'true', shape=(), dtype=string)
b'true'


In [ ]:
#Special constants
a=tf.zeros(shape=[2,2])
b=tf.ones(shape=[3,3])
print(a)
print(b)
print(a.numpy())
print(b.numpy())

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import tensorflow as tf
tf.config.run_functions_eagerly(True)
a=tf.constant([[2,3],[1,2]])
b=tf.constant([[2,2],[2,2]])
c=tf.multiply(a,b)
result=a*b
print(result)
print(result.numpy())


tf.Tensor(
[[4 6]
 [2 4]], shape=(2, 2), dtype=int32)
[[4 6]
 [2 4]]


In [ ]:
print(c)
print(c.numpy())

tf.Tensor(
[[4 6]
 [2 4]], shape=(2, 2), dtype=int32)
[[4 6]
 [2 4]]


In [ ]:
c=tf.matmul(a,b)
print(c)
print(c.numpy())

tf.Tensor(
[[10 10]
 [ 6  6]], shape=(2, 2), dtype=int32)
[[10 10]
 [ 6  6]]


In [ ]:
c=a@b
print(c)
print(c.numpy())

tf.Tensor(
[[10 10]
 [ 6  6]], shape=(2, 2), dtype=int32)
[[10 10]
 [ 6  6]]


In [ ]:
a=tf.constant([[1,2,3],[3,4,5]])
a.get_shape()

TensorShape([2, 3])

In [ ]:
a=tf.constant(1.25)
b=tf.cast(a,dtype=tf.int32)
print(a)
print(a.numpy())
print(b)
print(b.numpy())


tf.Tensor(1.25, shape=(), dtype=float32)
1.25
tf.Tensor(1, shape=(), dtype=int32)
1


In [ ]:
a=tf.constant([[1.,2.,3.],[3.,4.,5]])
b=tf.transpose(a)
print(b)
print(b.numpy())

tf.Tensor(
[[1. 3.]
 [2. 4.]
 [3. 5.]], shape=(3, 2), dtype=float32)
[[1. 3.]
 [2. 4.]
 [3. 5.]]


In [ ]:
b=tf.reduce_sum(a)
print(b)
print(b.numpy())

tf.Tensor(18.0, shape=(), dtype=float32)
18.0


In [ ]:
b=tf.concat([a,a,a],axis=0)
print(b.numpy())

[[1. 2. 3.]
 [3. 4. 5.]
 [1. 2. 3.]
 [3. 4. 5.]
 [1. 2. 3.]
 [3. 4. 5.]]


In [ ]:
x=tf.constant([[20,30,40,60,70]])
logits=tf.constant([20,30,40,60,70],dtype=tf.float32)
softmax_probs=tf.nn.softmax(logits,axis=-1)
print(softmax_probs)


tf.Tensor([1.9286623e-22 4.2481610e-18 9.3571980e-14 4.5397868e-05 9.9995458e-01], shape=(5,), dtype=float32)
